### ISSUE TITLE
"Latest Version" issue fix doesn't have a release tag

### ISSUE THREAD

**Issue by AngleWyrm10** [pardeike/HarmonyRimWorld#13] opened 2021-03-16 00:51 UTC
Following the in-game link leads to the releases, and downloading the latest release doesn't resolve the version update flag. There has been a [commit](https://github.com/pardeike/HarmonyRimWorld/commit/39228e4016ac0e77fdbbac50e4ef973b91a38728) since then, which does resolve the issue but requires the user to take additional non-standard steps to get the zip and rename the folder.

Recommend adding release tag labeled with "1.1.0.0" to [that commit](https://github.com/pardeike/HarmonyRimWorld/commit/39228e4016ac0e77fdbbac50e4ef973b91a38728)

**Comment by pardeike** [comment] 2021-03-16 06:02
The release *is* the latest release. Not sure what you mean. Anything new is still in testing. 

The concept of a release is to mark a point in time of the repository where the content is verified and official. Any other changes are by definition work-in-progress.

**Comment by wzurborg** [comment] 2021-04-07 19:25
I think what he means is that on starting the mod 1.0.4.0 the mod manager shows a confusing message about a new version 1.1.0.0:

![Warning](https://snipboard.io/rVPHGC.jpg)
![Warning](https://snipboard.io/NK8kOa.jpg)

But that version is marked as pre-release and prototype, so 1.0.4.0 is the latest release.

Correct me if I am wrong.

**Comment by pardeike** [comment] 2021-04-07 20:14
And how about Mod Manager showing content of GitHub via master and not real releases. I up my version during development in order to not forget to increase it when I release and to distinguish versions for myself when testing.

But that does not mean that there is a release. It can go months until master is tagged with a release version. Sorry, not my problem.

**Closed as completed by pardeike** 2021-04-07 20:14 UTC

**Comment by wzurborg** [comment] 2021-04-08 07:42
I am sorry but your comment sounds a bit ignorant. I think it is a fair approach of the Mod Manager to look at the master branch, because not everybody works with releases in GitHub. According to common Git workflows you put prototypes and future releases on release branches until you are ready for an official release, and only then merge it into master. What is your problem of staying on a separate branch during testing?

**Comment by pardeike** [comment] 2021-04-08 10:56
Look, my mods were all on GitHub before Mod Manager even existed. I use git in the exact way it is designed for. That includes preparing the content in any way on master and then creating a release which automatically tags the content and fixes it in time. That’s how git works and that’s how I use it. 

Now someone creates a product that uses master and presents this fluent information as “released” to their users and you are blaming me to be ignorant. I would argue that the product design is ignorant. There is clearly a correct solution to this which I would use if I would be the author of that product: use the api to look for the latest release tag, get the commit id from that and use the api to fetch files from that commit state instead of using master. 

I want you to complain to the right person here which is the author of the Mod Manager.

**Comment by pardeike** [comment] 2021-04-08 11:01
*What is your problem of staying on a separate branch during testing?* I just don’t want to do it. Who says that this is the only way? I don’t like to be forced to a workflow that someone else determines for me. Especially if there is a solution that solves it. I call this “creating a problem and then solving it”. I prefer to not create the problem in first place by designing a solution that does not force others to do stuff they don’t like.

**Comment by pardeike** [comment] 2021-04-08 11:02
Btw, I am German and by definition a total ignorant asshole.

**Comment by wzurborg** [comment] 2021-04-08 14:27
> 
> 
> Btw, I am German and by definition a total ignorant asshole.

Ein perfektes Schlusswort. Dem möchte ich dann auch nichts mehr hinzufügen. :satisfied:
